language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: JdMINnKFTmPqr1IRzhTvEbkULWq/D+UhUk+CkD3vdVBsrIiJ8TDLPkYeFPx8U1otKLIefMd/RZ8zM2oaqSNYosFGGc3mjmCe2m+Nb4icSkOH4+GgaCMDi8Zso6rRNPdHeb4FuE8hYlhNPVWu6pJnK+K3u672yG0eXG4mcj90z5fcZzxJrSgB5nj7By5Slk4CZJKxeY/KSpW+4Dsqf61b9k9Jmf9oKcCLW5pFTyCJnHy0h+c3Cz31raPWs2UmT0e38zIgbBGEy1pOZysLLwPlo7kLwF7d0kJJ34FQx7KGRlxLBVXLsR+iug0F/9NpD4jnhWxZWC4huuCExQ7uP2wD7ut/YbHwhS4EST4k/A9hv/EBcDx+G4rWk0xGLpeQnR2os59D9IHnzP6jA7mhVXFBIysH7Dm7fKa8NgsAjIqJNhvGNg6GVq42x5hf3ZNn1MTW+xervK5yHl5yVCxf4tNxB9I9vCegTk3GMUO7epGLSwGHoDOERKbk33+5OTS6bTKpw2FfR5jfHIXEkuKDCG56zQEJK8hToEi5K9K6+Z5nISUTTJ+HZmmImuBHYIvfCTH3Z/yZOpa9lDTJH6l6yKobqlDJ9cHt+rWvKfTXpYIhzERhJzxiV8m/geD86Bz3l14qfTFr9QRxk4B8+ieCOCLEzj6wPw5VGHXnELMPCIN4tSY=
  app: travel-buddy-api
  run: rails db:migrate
  on:
    repo: antoniojking/travel_buddy_be
    branch: main
env:
  global:
  - secure:
  - secure: NquCYQAhHsuvllzTxsLcjN9PvtHPJ3OE4dgeDxmR99JKY7QYcn+OUpF6YPeBPVR8+XSJU+cQ3NANvs7SqW6JciFRMFh8WBv6GVapJolaHOMVyrEH0bInaiu7t8z1dpI0lMYBpxuVlVyQPDnCzYBS0/tDH8/snbHT9AtvO0vbTrm7W/dJz4TPhQs1Neo659tdiQKdwzS16RtAYkKHvN7r9CjSY9yC0jqCAt94Bqdts0d6pbI4HEDFQzTJKHVBdar/gQAMBUCjrPnPZPKPIO1XSob3v6h/Fz+mQtQyqS+ZfByoPkIYZq7HNFs1ehbJoHoeb9sOfKrr4vIVCIc2Q2VoVyHdB4l8OzxJh1x0YVLpqE9RwF1wWe3naJSgxE2+vTa5PxWRMXvXNUmfcun8X9d2rJzUKLibEEQqQntA+GqjajjxLEmGJv41mDJi9k2ZTlLONlk5blPeMhRuOrE7aWi+4BHE8Qnadx0laGLA7a7Jx/CZidkKz9ZbpOlYNmt1LdEu9/tUpxzxpcMLGcP5/5PpK8xF7RhPBJzG84bXHVpvIWpCHl42Zufsq2e1N1OarH5rus5TpkjLxJF+sdZjogXCOWc3yOi8+CyoCZmlrvq8CJpQU7ZbMECKpFp5mMPDFN9baq6Ssv9Tl8GDLnvWjOsUx0oHrTjc9MlzYdcPVj83FyU=
  - secure: Cly/f4+bE6j1Z4cZ97U5xJOSLmZA2uyQ4q1+U+9tfyD87R2ijIlPkZp/C/dbSFPp/GmOTggCc50SjhAGfXn8k19L50MIFm7OpZKgaUGvxV0Ehhy5vs8Q4sWGu/RNAa0ykYBvpEn2toAhUtaY3BS0BK+YHuOOnsXt0llxsO1oRZoDOO91IZinsVHHy7GwGI7t9XgyHxNF0e+TTf+qISLsHSYdAjjpfcbjwsOFTX+eUPSWd3NuC6RjXowynXnNCeUzNetB+2tEvN/8bvE3kP7eVf0Q9sHvcAc+W381P5wWgWsSypnCyDRtswVea+BfLM/0Yz4m1Y7otrkK23Ksjcpw8aRtLSguHHcxyD4lr9H5tmdmrHxrAEmofJEhd8KaTep1VuavA8PlyQp6EHl1MRw0EnI9UGV1iFGl0y5+N3x18TTwDBSSOORCP8ezcYApDB9rgv9bkMseFnWuzDCRYzDAJxbcEpAFj5+RHqglBjD5yDJ2Dpo7ShpgcWeN/WPFhiokQYJCAPWsCAWFin8F2xPbglAeOjEBfav71ha2Qk9d2XBs+gZCtvtyZLexYq6f2iHCXWiuMxmwl9zTbK8/NOIh2ZtMOVW/xVjTVTZPg65KWd2rjnUli03oAI831w07iOe5hBTch1AzznuPcyMxSf9ygAJ3wS3oh6qgMItMTm0J4rQ=
before_install:
  - yes | gem update --system --force
  - gem install bundler
